name: Create release and asset

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  release:
    types: 
      - published
env:
  # Pretty cargo output!
  CARGO_TERM_COLOR: always

jobs:
  # Publish docker multiarch image to GitHub Container Registry
  push-image-ghcr:
    name: Push docker multiarch image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/amd64/v2,linux/arm64/v8
          push: true
          build-args: |
            BUILD_VERSION=${{ github.event.release.tag_name }}
          tags: |
            ghcr.io/adempiere/s3-gateway-rs:${{ github.event.release.tag_name }}
            ghcr.io/adempiere/s3-gateway-rs:latest
